// <auto-generated />
using ContactListRazorViews.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactListRazorViews.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220820182038_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("ContactListRazorViews.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            EmailAddress = "beoulve.iv@gmail.com",
                            FirstName = "Ramza",
                            LastName = "Beoulve",
                            PhoneNumber = ""
                        },
                        new
                        {
                            ContactId = 2,
                            EmailAddress = "agrias.oaks@gmail.com",
                            FirstName = "Agrias",
                            LastName = "Oaks",
                            PhoneNumber = "+44 128 478 364"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
